### ISSUE TITLE
Tracking roles and Attribution in campaigns and deliverables

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-awareness#38]
In order to give the proper Attribution when a deliverable is produced (e.g. in the credit role of a video), and to provide clarity on who is working on a particular Campaign and Deliverable, we should add some fields, like 'Original idea', 'Coordinator', etc. which appears in the `Info` section of the documents.

- [x] Add 'Coordinator' and 'Original idea' fields to `Info` section of Campaigns and Deliverables
- [x] Update information model accordingly
- [x] Update Issue templates accordingly
- [x] Report to Campaigners group on changes made.

**Comment by patmatsu** [comment]
Thanks for posting this. It relates to the RFP Georges wrote. When I met with a friend yesterday to discuss the RFP, he pointed out that there needs to be a personnel section--e.g., director, scriptwriter, crew, etc.--so that the various roles are differentiated.

**Comment by aschrijver** [comment]
Yes. On the Deliverable there was already a `Team` field, but that should also be in campaign properly, independent of the above two fields in the `Info` section.

**Comment by aschrijver** [comment]
I created a task list in the issue and assigned to myself.

**Comment by aschrijver** [comment]
Reported the changes to Campaigners group. All tasks done. Closing.
