### ISSUE TITLE
Create Strategy Guidelines documentation

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-awareness#40]
General strategy practices and approach should be documented in a Strategy Guidelines document in `/strategy/strategy-guidelines.md`.

This is a top-level issue with the tasks needed to create an initial version:

- [ ] Create document, with initial header structure and ToC
- [ ] Document approach, procedures and best-practices for crowdfunding (#9)
- [ ] Document approach to actual tech companies (#23)
- [ ] Document procedures for drafting RFP's and link to RFP template(s) (#14)
- [ ] Add header + summary on Hackathons, and link to `strategy/hackathons.md` doc
