### ISSUE TITLE
Tracking affiliation in campaigns and deliverables

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-awareness#42]
Both Campaigns and their Deliverables can have official support by the HTC and/or CHT, but it is also possible that they cover Humane Tech awareness activities that are not fully supported.

To distinguish between officially supported or not, both Campaigns and Deliverables will have a `Affiliation` field, that can be either `Official`, or `Unofficial`.

- [x] Update information model with Affiliation field
- [x] Update existing proposals
- [x] Update issue templates

**Comment by aschrijver** [comment]
All tasks done. Closing.
